server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  mvc:
    static-path-pattern: /img/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: classpath:/static/,file:/upload/


log:
  path: D:/data/logs
logging:
  file:
    name: ${log.path}/springboot_study.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %highlight([%level]) %logger{15} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${log.path}/springboot_study-%d{yyyy-MM-dd}.%i.gz #日志文件会根据日期进行滚动，文件大小达到指定的最大值会进行压缩
      max-file-size: 50MB #设置单个日志文件的最大大小为50MB。当文件达到这个大小时，会触发滚动。
      max-history: 10  #设置保留日志文件的最大历史天数为10天






